ack.write.path=D:\\AMS2.0\\BACKUP\\ACK\\
ktnet.write.path=D:\\AMS2.0\\FTP\\KTNET\\SEND\\
fhl.write.path=D:\\AMS2.0\\BACKUP\\FHL\\
typeb.write.path=D:\\AMS2.0\\BACKUP\\TYPEB\\
ktnet.ams.write.path=D:\\AMS2.0\\BACKUP\\KTNETAMS\\
ktnet.fhl.write.path=D:\\AMS2.0\\BACKUP\\KTNETFHL\\
kcnet.fhl.write.path=D:\\AMS2.0\\BACKUP\\KCNETFHL\\
file.errorDir=D:\\AMS2.0\\ERROR\\
#AMQ 97
amq97.url=tcp\://203.251.151.87\:61616
amq97.id=traxon01
amq97.pw=tr@xon1234
#AMQ 98
amq98.url=tcp\://203.251.151.87\:61616
amq98.id=traxon01
amq98.pw=tr@xon1234
#AMS DB
amsdb.url=jdbc\:oracle\:thin\:@172.16.100.10\:1531\:GLDEV
amsdb.id=AMSTEST
amsdb.pw=AMSTEST
#MSB DB
msbdb.url=jdbc\:oracle\:thin\:@172.16.100.12\:1531\:GLMSB
#msbdb.url=jdbc\:oracle\:thin\:@172.16.100.10\:1531\:GLDEV
msbdb.id=TRAXON
msbdb.pw=TRAXON41#
#msbdb.id=MSBTEST
#msbdb.pw=MSBTEST
ikams.done.yn=F
#TW TYPEB
bkk.addr=BKKF2TG BKKF5TG BKKFMTG DXBFMTG HDQFDTG ICNACXH ICNKKTW
pnh.addr=BKKF2TG BKKF5TG BKKFMTG DXBFMTG HDQFDTG ICNACXH ICNKKTW
sgn.addr=SGNCRXH SGNFKXH SGNSCXH HANSWXH DADFFXH DADKKXH ICNACXH ICNKKTW
handad.addr=HANSWXH HANFIXH DADFFXH DADKKXH ICNACXH ICNKKTW
nrt.addr=NRTCWCR NRTFGXH NRTFIXH ICNACXH ICNKKTW
jfk.addr=NRTCWCR NRTFGXH NRTFIXH ICNACXH ICNKKTW
kix.addr=CHACSJL KIXFTJL ICNACXH ICNKKTW
tao.addr=TAOFC1E ICNACXH ICNKKTW
vte.addr=VTEHHXH ICNACXH ICNKKTW
#ZE TYPEB
zejpn.addr=SELTPZE NRTFIXH NRTCWCR NRTFGXH TYONDXH