ack.write.path=D:\\AMS2.0\\BACKUP\\ACK\\
ktnet.write.path=D:\\AMS2.0\\FTP\\KTNET\\SEND\\
fhl.write.path=D:\\AMS2.0\\BACKUP\\FHL\\
typeb.write.path=D:\\AMS2.0\\BACKUP\\TYPEB\\
ktnet.ams.write.path=D:\\AMS2.0\\BACKUP\\KTNETAMS\\
ktnet.fhl.write.path=D:\\AMS2.0\\BACKUP\\KTNETFHL\\
kcnet.fhl.write.path=D:\\AMS2.0\\BACKUP\\KCNETFHL\\
file.errorDir=D:\\AMS2.0\\ERROR\\
#AMQ 98
amq98.url=tcp\://10.119.163.51\:61616
amq98.id=admin
amq98.pw=admin
#AMQ 97
amq97.url=tcp\://10.119.163.51\:61616
amq97.id=admin
amq97.pw=admin    
#AMS DB
amsdb.url=jdbc\:oracle\:thin\:@trxdev-dd.cy7ymldio5s7.ap-northeast-2.rds.amazonaws.com\:1531\:TRXDEV
amsdb.id=AMSTEST
amsdb.pw=oj4-0IR}WudNTc$B+g`C#O~xFwUW|T
#MSB DB
msbdb.url=jdbc\:oracle\:thin\:@trxdev-dd.cy7ymldio5s7.ap-northeast-2.rds.amazonaws.com\:1531\:TRXDEV
msbdb.id=MSBTEST
msbdb.pw=l6D;25_HiwE{g0?dfl|z=l60+[^^{z
ikams.done.yn=F
#ZE TYPEB
zejpn.addr=SELTPZE NRTFIXH NRTCWCR NRTFGXH TYONDXH

#########
