#
# The logging properties used
#
log4j.rootLogger=INFO, out, FileAppender

# uncomment the following line to turn on Camel debugging
#log4j.logger.org.apache.camel=DEBUG

log4j.logger.org.springframework=WARN

# CONSOLE appender not used by default
log4j.appender.out=org.apache.log4j.ConsoleAppender
log4j.appender.out.layout=org.apache.log4j.PatternLayout
#log4j.appender.out.layout.ConversionPattern=[%30.30t] %-30.30c{1} %-5p %m%n
#log4j.appender.out.layout.ConversionPattern=%d [%-5p] [%t] [%C{1}] (%F:%L) - %m%n
#log4j.appender.out.layout.ConversionPattern=[%30.30t] [%t] %d - %m%n
#log4j.appender.out.layout.ConversionPattern=%d [%-15.15t] %-5p %-30.30c{1} - %m%n
log4j.appender.out.layout.ConversionPattern=%d [%t] - %m%n

log4j.logger.java.sql=INFO
#log4j.logger.java.sql=DEBUG
#log4j.logger.java.sql.Connection=INFO
#log4j.logger.java.sql.Statment=INFO
#log4j.logger.java.sql.PreparedStatment=INFO
#log4j.logger.java.sql.ResultSet=INFO

# Daily file appender
log4j.appender.FileAppender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FileAppender.File=/DEAMON/AMS_MAIN/log/ams2.0_main.log
#log4j.appender.FileAppender.File=/data/GL/Client/log/test/test_MQ.log
#log4j.appender.FileAppender.File=log/ams2.0_main.log
#log4j.appender.FileAppender.File=${logdir}
log4j.appender.FileAppender.layout=org.apache.log4j.PatternLayout
#log4j.appender.FileAppender.layout.ConversionPattern=[%30.30t] [%t] %d [%-5p] [%t] [%C{1}] (%F:%L) - %m%n
log4j.appender.FileAppender.layout.ConversionPattern=%d [%-5p] [%t] [%C{1}] (%F:%L) - %m%n
log4j.appender.FileAppender.Append=true
log4j.appender.FileAppender.DatePattern='.'yyyy-MM-dd